/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as CatalogRouteImport } from './routes/catalog';
import { Route as IndexRouteImport } from './routes/index';
import { Route as SessionFingerprintRouteImport } from './routes/session.$fingerprint';
import { Route as AuthCallbackRouteImport } from './routes/auth.callback';

const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const SessionFingerprintRoute = SessionFingerprintRouteImport.update({
  id: '/session/$fingerprint',
  path: '/session/$fingerprint',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/catalog': typeof CatalogRoute;
  '/auth/callback': typeof AuthCallbackRoute;
  '/session/$fingerprint': typeof SessionFingerprintRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/catalog': typeof CatalogRoute;
  '/auth/callback': typeof AuthCallbackRoute;
  '/session/$fingerprint': typeof SessionFingerprintRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/catalog': typeof CatalogRoute;
  '/auth/callback': typeof AuthCallbackRoute;
  '/session/$fingerprint': typeof SessionFingerprintRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/catalog' | '/auth/callback' | '/session/$fingerprint';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/catalog' | '/auth/callback' | '/session/$fingerprint';
  id:
    | '__root__'
    | '/'
    | '/catalog'
    | '/auth/callback'
    | '/session/$fingerprint';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  CatalogRoute: typeof CatalogRoute;
  AuthCallbackRoute: typeof AuthCallbackRoute;
  SessionFingerprintRoute: typeof SessionFingerprintRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/catalog': {
      id: '/catalog';
      path: '/catalog';
      fullPath: '/catalog';
      preLoaderRoute: typeof CatalogRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/session/$fingerprint': {
      id: '/session/$fingerprint';
      path: '/session/$fingerprint';
      fullPath: '/session/$fingerprint';
      preLoaderRoute: typeof SessionFingerprintRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/auth/callback': {
      id: '/auth/callback';
      path: '/auth/callback';
      fullPath: '/auth/callback';
      preLoaderRoute: typeof AuthCallbackRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogRoute: CatalogRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  SessionFingerprintRoute: SessionFingerprintRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
